[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#030C03"

# Background color for the main content area.
backgroundColor = "#0EBB07"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#0C0E16"

# Color used for almost all text.
textColor = "#1DF310"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"

